version: "GETHERE"

services:
    database_ignite:
        image: postgresa
        container_name: GETHERE
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=GETHERE
            - POSTGRES_PASSWORD=GETHERE
            - POSTGRES_DB=GETHERE
        volumes:
            - pgdata:/data/GETHERE

    app:
        build: .
        container_name: GETHERE
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app

volumes:
    pgdata:
        driver: local
